version: '3'

services:
  grc:
    container_name: grc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web_nw
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=.
      - DEFAULT_EMAIL=${DEFAULT_EMAIL:-admin@example.com}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD:-admin}
      - VERSION=${VERSION:-3.4.3}
      - APP_NAME=GRC
      - GUNICORN_WORKERS=2
      - MAIL_USERNAME=notification@saltsquare.io
      - AWS_PROFILE
      - SQLALCHEMY_DATABASE_URI
      - EVIDENCE_BUCKET
      - GRAPH_APP_ID
      - GRAPH_APP_SECRET
    volumes:
      - .:/server
      - ~/.aws:/root/.aws
    command: >
      /bin/sh -c " \
        alembic upgrade head; \
         gunicorn --bind 0.0.0.0:5000 flask_app:app --access-logfile '-' --error-logfile "-" --timeout 600
      "

networks:
  web_nw:
    driver: bridge
