{{- if .Values.gappsSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gapps-secrets
type: Opaque
data:
  {{- with .Values.gappsSecrets }}
    {{- range $key, $value := . }}
      {{- if ne $key "enabled" }}
  {{ $key }}: {{ $value | b64enc | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
